"""add email_verification_token

Revision ID: a72c7d3df839
Revises: ed31f537e5b9
Create Date: 2026-05-23 08:48:04.956027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a72c7d3df839'
down_revision = 'ed31f537e5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_verification_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_verification_token_token'), ['token'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token_expiry')
        batch_op.drop_column('verification_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    with op.batch_alter_table('email_verification_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_verification_token_token'))

    op.drop_table('email_verification_token')
    # ### end Alembic commands ###
