"""add cloudinary public_id

Revision ID: ed31f537e5b9
Revises: 7ccaea7024e0
Create Date: 2026-05-22 22:58:17.442403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed31f537e5b9'
down_revision = '7ccaea7024e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_public_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('image_public_id')

    # ### end Alembic commands ###
